name: JavaWorkflow

on: 
  workflow_dispatch:
  push:
    branches: 
      - main
env:
  grussformel: Hallo

jobs: 
  build-test:
    runs-on: ubuntu-latest
    needs: ausgabe
    if: always()

    strategy:
      matrix:
        version: [11,17,21]
        
    steps:
      - name: Test JDK version
        run: echo Version ${{matrix.version}}
        
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{matrix.verison}}
          
      - name: Build and Test with Maven
        run: mvn -B clean verify

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/
          
  linter-test:
    runs-on: ubuntu-latest
    needs: ausgabe
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Lint Test
        run: mvn checkstyle:checkstyle

      - name: upload lint
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: target/checkstyle-result/

  ausgabe:
    runs-on: ubuntu-latest
    env:
      begruss: Ich

    steps:
      - name: Set passnutz
        env:
          passnutz: Bank
        run: echo $grussformel
